// Exercise the workspace with deterministic account states; never use live accounts.
import "./kits.mjs";
import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { chromium } from "playwright-core";
const server=spawn(process.execPath,["dist/cli.js","ui","--port","41406","--no-open"],{env:{...process.env},stdio:["ignore","pipe","pipe"]});
let browser;
try {
  await new Promise((resolve,reject)=>{
    const timer=setTimeout(()=>reject(new Error("Console startup timeout")),10000);
    server.on("exit",code=>{clearTimeout(timer);reject(new Error(`Console exited ${code}`));});
    server.stdout.on("data",data=>{if(String(data).includes("41406")){clearTimeout(timer);resolve();}});
    server.stderr.on("data",data=>process.stderr.write(data));
  });
  const base="http://127.0.0.1:41406";
  const original=(await (await fetch(base+"/api/processes")).json())[0];
  const account={...original,id:"ads-openai/main-account",goal:{...original.goal,metric:"Click-through rate"},experiments:[],signed_in_at:Date.now(),learning:{state:"ready",active:false,message:"Account observations saved. Review the grounded suggestions below.",at:Date.now()},kits:original.kits.filter(k=>k.state==="ready").slice(0,1)};
  assert.equal(account.kits.length,1);
  const accounts=[account,{...account,id:"ads-openai/new-campaign",kits:[],goal:null,candidates:[],learning:{state:"needs-signin",active:false,message:"Sign in to read the account."},signed_in_at:null}];
  browser=await chromium.launch({channel:"chrome",chromiumSandbox:true,headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1100},reducedMotion:"reduce"});
  const errors=[];page.on("pageerror",e=>errors.push(e.message));
  await page.route("**/*",route=>{
    const url=route.request().url();
    if(url===base+"/api/processes") return route.fulfill({json:accounts});
    if(url===base+"/api/kits/launched") {
      const body=route.request().postDataJSON();
      const kit=account.kits.find(k=>k.id===body.id);
      Object.assign(kit,{state:"launched",launched_at:Date.now(),launch_note:body.note});
      return route.fulfill({json:{ok:true}});
    }
    if(url===base+"/api/add") {
      const body=route.request().postDataJSON();
      accounts.push({...account,id:body.id,kits:[],goal:null,candidates:[],learning:null,signed_in_at:null});
      return route.fulfill({json:{ok:true}});
    }
    if(url===base+"/api/connectors/delete") return route.fulfill({status:400,json:{error:"Cancel the browser task and wait for it to stop before deleting this connector."}});
    return url.startsWith(base)?route.continue():route.abort();
  });
  await page.goto(base);
  await page.getByRole("heading",{name:"Small experiments. Better possibilities."}).waitFor();
  assert.equal(await page.locator("#proc-table tr.row").count(),2);
  await page.screenshot({path:"/tmp/openxpli-workspace-desktop.png",fullPage:true});
  await page.locator('[data-workspace-filter="ready"]').click();
  assert.equal(await page.locator("#proc-table tr.row").count(),1);
  await page.getByRole("searchbox",{name:"Filter connectors"}).fill("no-such-connector");
  await page.getByRole("heading",{name:"No matching connectors"}).waitFor();
  await page.getByRole("button",{name:"Clear filters"}).click();
  assert.equal(await page.locator("#proc-table tr.row").count(),2);
  await page.locator('[data-select-connector]').first().click();
  if(!await page.locator('.focus-card').count()) await page.locator('[data-select-connector]').first().click();
  await page.locator('.focus-card [data-workspace-jump="kits"]').click();
  await page.getByRole("link",{name:"Download complete kit",exact:true}).waitFor();
  await page.screenshot({path:"/tmp/openxpli-workspace-kit.png",fullPage:true});
  await page.evaluate(()=>{
    window.__procs[0].map="## Campaigns\n**Brand campaign** is active.\n- Budget: $100/day\n- Goal: qualified visits\n\n<script>window.evidenceUnsafe=true</script>";
    window.__evidenceCandidates=window.__procs[0].candidates;
    window.__procs[0].candidates=[{...window.__procs[0].candidates[0],evidence:[{url:"https://ads.example.test/campaigns/brand",text:"Brand campaign: $100/day",observedAt:1700000000000},{url:"javascript:alert(1)",text:"Untrusted source",observedAt:null}]}];
    openKnowledge(window.__procs[0].id);
  });
  const evidenceDialog=page.getByRole("dialog",{name:"Account evidence",exact:true});
  await evidenceDialog.getByRole("heading",{name:"Campaigns",exact:true}).waitFor();
  assert.ok(await evidenceDialog.locator('.evidence-source').count()>=2);
  assert.equal(await evidenceDialog.locator('a[href^="javascript:"]').count(),0);
  assert.equal(await page.evaluate(()=>window.evidenceUnsafe),undefined);
  await evidenceDialog.getByText("Read captured page text",{exact:true}).first().click();
  await evidenceDialog.getByText("Brand campaign: $100/day",{exact:true}).waitFor();
  await page.screenshot({path:"/tmp/openxpli-account-evidence.png"});
  await page.setViewportSize({width:390,height:844});
  assert.equal(await evidenceDialog.evaluate(el=>el.scrollWidth<=el.clientWidth),true);
  await page.keyboard.press("Escape");
  assert.equal(await evidenceDialog.count(),0);
  await page.evaluate(()=>{window.__procs[0].candidates=window.__evidenceCandidates;});
  await page.setViewportSize({width:1440,height:1100});
  const context=page.locator('.context-details[data-disclosure^="settled-"]');
  await context.locator('summary').click();
  await page.evaluate(()=>{const copy=structuredClone(window.__procs);copy[0].tool="ChatGPT Ads updated";renderProcesses(copy);});
  assert.equal(await context.getAttribute("open"),"");
  // Destructive controls are available without expanding the connector.
  await page.locator('.connector-menu summary').first().click();
  await page.getByRole("button",{name:"Delete connector",exact:true}).click();
  const dialog=page.getByRole("dialog");
  await dialog.waitFor();
  await page.locator('#form-submit').focus();
  await page.keyboard.press("Tab");
  assert.equal(await page.evaluate(()=>document.activeElement.getAttribute("aria-label")),"Close dialog");
  await page.locator('#form-submit').click();
  await page.locator('#form-error').getByText("Cancel the browser task",{exact:false}).waitFor();
  assert.equal(await page.locator('#form-submit').isEnabled(),true);
  await page.keyboard.press("Escape");
  assert.equal(await dialog.count(),0);
  assert.equal(await page.locator('#view-processes').evaluate(el=>el.inert),false);
  await page.setViewportSize({width:390,height:844});
  await page.evaluate(()=>document.getElementById("view-processes").scrollTo(0,0));
  await page.screenshot({path:"/tmp/openxpli-workspace-mobile.png",fullPage:true});
  await page.locator('.focus-card [data-workspace-jump="kits"]').click();
  await page.screenshot({path:"/tmp/openxpli-workspace-mobile-kit.png",fullPage:true});
  const overflow=await page.evaluate(()=>({body:document.body.scrollWidth,viewport:innerWidth,main:document.getElementById("view-processes").scrollWidth,client:document.getElementById("view-processes").clientWidth}));
  assert.ok(overflow.body<=overflow.viewport && overflow.main<=overflow.client,JSON.stringify(overflow));
  await page.setViewportSize({width:1440,height:1100});
  await page.getByRole("button",{name:"Add connector",exact:false}).first().click();
  await page.getByRole("dialog",{name:"Bring an account into focus"}).waitFor();
  await page.locator('[data-add-tool="ads-openai"]').click();
  await page.getByRole("textbox",{name:"Connector name"}).fill("ads-openai/new-account");
  await page.locator('#form-submit').click();
  await page.getByRole("button",{name:"ads-openai/new-account",exact:false}).first().waitFor();
  assert.ok(page.url().includes("connector=ads-openai%2Fnew-account"));
  assert.equal(page.context().pages().length,1,"adding a connector must not open an unrelated auth tab");
  await page.locator('[data-workspace-filter="ready"]').click();
  await page.reload();
  assert.equal(await page.locator('[data-workspace-filter="ready"]').getAttribute("aria-pressed"),"true");
  await page.locator('#proc-table tr.row').waitFor();
  assert.equal(await page.locator('#proc-table tr.row').count(),1);
  await page.locator('[data-workspace-filter="all"]').click();
  await page.locator('[data-select-connector="ads-openai/main-account"]').first().click();
  if(!await page.locator('.focus-card').count()) await page.locator('[data-select-connector="ads-openai/main-account"]').first().click();
  await page.locator('.focus-card [data-workspace-jump="kits"]').click();
  await page.getByRole("button",{name:"I launched this myself",exact:true}).click();
  await page.locator('#kit-launch-note').fill("Control A, variant B");
  await page.locator('#kit-launched-check').check();
  await page.locator('#form-submit').click();
  await page.getByRole("dialog").waitFor({state:"detached"});
  assert.equal(await page.locator('[data-workspace-section="kits"]').count(),0);
  const history=page.locator('[data-workspace-section="kit-history"]');
  assert.equal(await history.locator("xpath=ancestor::details[1]").getAttribute("open"),null);
  assert.equal(await page.getByRole("link",{name:"Download complete kit",exact:true}).isVisible(),false);
  await page.locator('.focus-card [data-workspace-jump="kit-history"]').click();
  if(await history.locator('[data-kit-action="toggle"]').getAttribute("aria-expanded")!=="true") await history.locator('[data-kit-action="toggle"]').click();
  await history.getByText("Your launch notes: Control A, variant B").waitFor();
  await history.getByRole("link",{name:"Download complete kit",exact:true}).waitFor();
  await page.evaluate(()=>refresh());
  assert.equal(await history.locator("xpath=ancestor::details[1]").getAttribute("open"),"");
  // A fresh visit keeps launch history collapsed.
  await page.reload();
  await history.waitFor({state:"attached"});
  assert.equal(await history.locator("xpath=ancestor::details[1]").getAttribute("open"),null);
  accounts.splice(0);
  await page.evaluate(()=>refresh());
  await page.getByRole("heading",{name:"Your next good idea starts here."}).waitFor();
  await page.evaluate(()=>document.getElementById("view-processes").scrollTo(0,0));
  await page.screenshot({path:"/tmp/openxpli-workspace-empty.png",fullPage:true});
  assert.deepEqual(errors,[]);
  console.log("PASS: workspace filters, honest empty state, kit navigation, preserved disclosure, modal keyboard loop, inline errors, mobile overflow, onboarding handoff, bookmarkable filters, and launched kit history");
} finally {if(browser) await browser.close();server.kill("SIGTERM");}
